pipeline:
  check:
    image: rust
    commands:
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo check
      - cargo fmt --check
      - cargo clippy --no-deps -- -Dwarnings