pipeline:
  check:
    image: rust
    commands:
      - echo "Installing components..."
      - rustup component add rustfmt
      - rustup component add clippy

      - echo "Checking build..."
      - cargo check --quiet

      - echo "Checking formatting..."
      - cargo fmt --check -- quiet

      - echo "Checking lints..."
      - cargo clippy --no-deps --quiet -- -Dwarnings