pipeline:
  check:
    image: rust
    commands:
      - rustup component add rustfmt
      - rustup component add clippy

      - cargo check --quiet
      - cargo fmt --check --quiet
      - cargo clippy --no-deps --quiet -- -Dwarnings