version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 8031:5432
    environment:
      - POSTGRES_DB=fdl

  api:
    image: fdl-mc/api/economy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
    ports:
      - 8030:8000
    depends_on:
      - db
