version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 8021:5432
    environment:
      - POSTGRES_DB=fdl
      - POSTGRES_USER=fdl
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  api:
    image: fdl_economy_service
    restart: always
    environment:
      - DATABASE_URL=postgresql://fdl:${POSTGRES_PASSWORD}@db/fdl
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
    ports:
      - 8020:8020
    depends_on:
      - db