[package]
name = "economy-service-entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "0.10.1", features = ["macros", "runtime-tokio-rustls", "sqlx-all"] }
serde = { version = "1.0", features = ["derive"] }
